### ISSUE TITLE
configs folder

### ISSUE THREAD

**Issue by Factral** [heng-yuwen/MatSpectNet#1]
can you upload the yaml configuration files to run the project?

**Comment by heng-yuwen** [comment]
Hi @Factral, I am reconstructing the code to provide a clean git repo. Sorry, but this may take longer than expected since I am focusing on my PhD graduation.

**Comment by heng-yuwen** [comment]
Also, @Factral , to speed up your research, my suggestion is to ignore the physical camera model and the domain adaptation method in my paper for now. Just use MST++ to recover HSI from RGB images, and use the filter and MLP I proposed, and merge the extracted information to your task. You should see improvement if your task depends on the material optical property.

**Comment by Factral** [comment]
Thank you very much, and best of luck with your PhD graduation.

 I was wondering if I could ask you about the multi-modal fusion aspect once we have the HSI image. Specifically, I'm curious about how you create the spectra shape for the HSI and spectraldb. 

I came across this file  [shape_metrics.npy](https://github.com/heng-yuwen/MatSpectNet/blob/main/data/spectraldb/shape_metrics.npy) that has dimensions of *1294x465*. I understand that 1294 corresponds to the number of materials in SpectralDB, but I'm unsure about the significance of 465. I looked at the code and the paper, which involves calculating `abs(spectra[i-1:30] - spectra[i:])`, but I'm having trouble grasping the intuition behind this operation, and why just dont compare with a matrix of shape *1294 (materials) x 31 (bands)*

**Comment by heng-yuwen** [comment]
Hi @Factral, this is a very good question. In fact, you can compare using the spectra measurement directly. However, this could cause a problem due to the sensitivity and precision of the spectra measurement equipment. The spectral camera is less accurate compared with a spectrometer. Therefore, I propose to use the curve shape to compare the spectra measurement rather than the direct measurement. This method is more robust than directing using the *31 bands*.
